delimiter $$
-- example of a trigger 
CREATE TRIGGER OOP BEFORE INSERT ON synthea.patients
FOR EACH ROW
BEGIN
IF NEW.HEALTHCARE_EXPENSES > HEALTHCARE_COVERAGE THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'ERROR: EXPENSES EXCEED COVERAGE, WILL REQUIRE OUT OF POCKET';
END IF;
END; $$
delimiter ;
show triggers;

-- Example of a function : 
DELIMITER $$
CREATE FUNCTION med_expense(expenses DECIMAL(10,2))
RETURNS VARCHAR(20)
BEGIN
DECLARE HEALTHCAREEXPENSES VARCHAR(20);
IF expenses > 1000 THEN
SET HEALTHCAREEXPENSES = 'high expense';
ELSEIF (expenses >= 100 AND
credit <= 1000) THEN
SET HEALTHCAREEXPENSES = 'medium expense';
ELSEIF expenses < 100 THEN
SET HEALTHCAREEXPENSES = 'small expense';
END IF;
-- return the medexpenses category
RETURN (HEALTHCAREEXPENSES);
END$$
DELIMITER ;
SELECT
Id,
HEALTHCARE_EXPENSES,
med_expense(HEALTHCARE_EXPENSES)
FROM
synthea.patients;